server:
  port: 9090
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ibma.j.walker99@gmail.com
    password: jwdl vshl rlbq vdex
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  security:
    user:
      name: ${SECURITYUSERNAME}
      password: ${SECURITYPASSWORD}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGREURL}
    username: ${POSTGREUSERNAME}
    password: ${POSTGREPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
java15:
  jwt:
    secret-key: ${JWTSECRETKEY}
    issuer: ${JWTISSUER}