server:
  port: 9090
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ibma.j.walker99@gmail.com
    password: ${password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  security:
    user:
      name: admin
      password: admin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sinemabiletdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  file:
    name: proje.log
  level:
    root: info #Büyükten küçüğe -> trace -> debug -> info -> warn -> error -> fatal -> off
#    com.ajwalker.controller.UserController: trace
java15:
  jwt:
    secret-key: 0f065e729f4f130a641c3a03751b50a7
    issuer: sinemBiletX